### ISSUE TITLE
Create About page

### ISSUE THREAD

**Issue by ShreyaPrasad1209** [Codess-Cafe/Codess-Cafe-Website#7]
The about page should contain:

- [ ] Navbar with "About" link active with white color
- [ ] "About" heading
- [ ] Add some content using [old website](https://codess.cafe/#about) as reference.
- [ ] Add [images](https://undraw.co/) from here.

Layout should be similar to that of homepage.

**Comment by nehagoyal2607** [comment]
Hi. I would like to work on this. Please assign it to me.
