### ISSUE TITLE
Create mentors page

### ISSUE THREAD

**Issue by ShreyaPrasad1209** [Codess-Cafe/Codess-Cafe-Website#9]
Mentors page should contain:

- [ ]  Navbar with "Mentor" link active in white color
- [ ]  "Mentor" heading
- [ ]  Add some content using [old website](https://codess.cafe/#mentors) as reference.
- [ ]  Add [images](https://undraw.co/) from here.

**Comment by navyaaaS1309** [comment]
I would like to work on this. Please assign it to me.

**Comment by navyasingla1309** [comment]
I would like to work on this. Please assign it to me!
